### ISSUE TITLE
[DOCS] README specifies requests-toolbelt as a dependency but it is not present in pyproject.toml nor source code

### ISSUE THREAD

**Issue by Sxderp** [python-rt/python-rt#106]
I think this is just a simple documentation error. I believe requests-toolbelt should be removed from the README.

**Comment by Sxderp** [comment]
Maybe the same for typing-extensions ?

**Comment by sim0nx** [comment]
Thanks for the hint. I removed that section from the doc as I don't think it is relevant. Up to date info can be found in pyproject.toml

Fixed in 08d4ae4e34950814d4a67852585a25a408a2363e
