### ISSUE TITLE
Custom field names containing spaces

### ISSUE THREAD

**Issue by danmichaelo** [python-rt/python-rt#38]
I discovered that custom field names can contain not just colons (#37), but also spaces :O

This seems a bit harder to support though. Retrieving them is no problem, but editing them doesn't work because `**kwargs` cannot contain spaces. A solution could be to translate underscores to spaces, so that this would work for updating the custom field `Some Field`:

```python
tracker.edit_ticket(ticket_id, CF_Some_Field='New value')
```

But this could potentially break things if someone is already using field names with underscores. So I'm not sure if it's a good idea.

**Comment by sebix** [comment]
I guess it is a lot easier with the RESTful API: #34

**Comment by brettcs** [comment]
While you can't write names with spaces directly in function calls, you can put them in a dictionary and then apply them as keyword arguments with `**`.

```python
>>> fields = {'CF_My Field': 'My Value'}
>>> '{CF_My Field}'.format(**fields)
'My Value'
```

Doing this lets you create and edit these fields using python-rt today. I have to use this approach to work with my own install, where we have some custom fields with `-` in the name, and that follows the same rules.

**Comment by danmichaelo** [comment]
@brettcs : Most interesting, I had no idea that was possible with Python 😮  This even works:

```python
>>> tracker.edit_ticket(ticket_id, **{'CF_Some Field': 'New value'})
```

**Comment by kimmoal** [comment]
I believe you can also use the numerical ID of the CF, like so: `CF_123`. Or in the raw query `CF.123`. The id is internal so I am not sure how "stable" it is if you delete / recreate the field.

**Comment by sebix** [comment]
I'm now wondering where best to document the mentioned workarounds. In the docstring of a function (`create_ticket`, `edit_ticket`, `search`) or the README itself, which does not mention custom fields yet?

**Comment by brettcs** [comment]
Full disclosure: I work at Best Practical now (started last May).

> I believe you can also use the numerical ID of the CF, like so: `CF_123`. Or in the raw query `CF.123`. The id is internal so I am not sure how "stable" it is if you delete / recreate the field.

That method will not do what you want if you delete the custom field and then create a new one with the same name. The upside is, it will continue to work if you rename the existing custom field. This lets you start writing code that handles it even if the name hasn't been finalized or you might want to modify it later.

> I'm now wondering where best to document the mentioned workarounds. In the docstring of a function (`create_ticket`, `edit_ticket`, `search`) or the README itself, which does not mention custom fields yet?

Given how the documentation is currently laid out, I think the function docstrings are where I would expect to find it. e.g., everywhere the docstrings currently talk about custom field names ("Custom fields CF.{<CustomFieldName>} could be set with keywords CF_CustomFieldName."), add a note that custom field names that aren't valid Python variable names can be stored in a dictionary and applied with `**`.

[This seems to be the simplest Python reference about the feature](https://docs.python.org/3/glossary.html#term-argument). I think [this is the most complete reference](https://docs.python.org/3/reference/expressions.html#calls) but that gets really deep in the weeds.

**Comment by sim0nx** [comment]
This should not be an issue anymore (at least not with REST v2)
