### ISSUE TITLE
RT cookie authentification

### ISSUE THREAD

**Issue by yshpishak** [python-rt/python-rt#66]
I am using the python 3.9 + RT 2.1.1 package to work with the Request Tracker software system.
I am facing difficulty in RT authentication using cookies. I have not found this documentation.
I ask for your help in solving this issue.

**Comment by wagner-certat** [comment]
Do the examples in https://github.com/CZ-NIC/python-rt/pull/60 help?

**Comment by yshpishak** [comment]
This is what I did today:
--------------------------------
cookies = {"RT_SID_OUTER-HEAVEN.80": "08141182b5991bcab49c56aca383bb51"}
tracker = rt.Rt(url='http://outer-heaven.local/rt/REST/1.0/', cookies=cookies)
tracker.login()

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/ys/PycharmProjects/RequestTracker/venv/lib/python3.9/site-packages/rt/rt.py", line 407, in login
    raise AuthorizationError('Credentials required, fill login and password.')
rt.exceptions.AuthorizationError: Credentials required, fill login and password.
-------------------------------------------------------------------------------------------------------------------------------------------------------
What should I do next. ?  Please show a working example. Thanks.

**Comment by sebix** [comment]
@kimmoal Is that correctly used?

**Comment by kimmoal** [comment]
You don't need to call login when you are using cookie authentication, you already should have a valid session. The login call of course fails because it is using default credentials. Correct code should just start using the tracker without any calls to login. Documentation of course should probably reflect this behaviour.

**Comment by kimmoal** [comment]
Rest2 I cannot say if cookies are supported, need to read some code :)

**Comment by sim0nx** [comment]
@jcharaoui in addtion to what @kimmoal  mentioned, what RT version are you using? REST v1 or v2 ?

**Comment by jcharaoui** [comment]
I wasn't able either using REST v1 and v2, using RT 4.4.4.  I was finally able to make it work via the auth token plugin.

**Comment by sim0nx** [comment]
ok :+1:
