### ISSUE TITLE
 get_attachments with only one transaction

### ISSUE THREAD

**Issue by INCIBE-CERT** [python-rt/python-rt#80]
Hello team,

While testing on RTIR, we have detected that `get_attachments` method is not parsing properly the content when there is only one attachment.

e.g.

```
RT/x.x.x 200 Ok

id: ticket/2000257/attachment
Attachments: 485: (Unnamed) (text/plain / 772b)
```

with more than one attachment, as you can see, there is a line break after the ticket id line.	

```
RT/x.x.x 200 Ok

id: ticket/2000126/attachment

Attachments: 234: (Unnamed) (text/plain / 799b),
             4519: (Unnamed) (text/plain / 1b)
```

In particular, we think the issue is in: https://github.com/python-rt/python-rt/blob/master/rt/rest1.py#L926

```python
if (self.__get_status_code(lines[0]) == 200) and (len(lines) >= 4):
	for line in lines[4:]:
		info = self.RE_PATTERNS['attachments_list_pattern'].match(line)
		if info:
			attachment_infos.append(info.groups())
```

We think in this case, if you are checking for four lines and more, you will need to specify lines[3:], because when there is only one attachment, the fourth line will be blank and it will fail getting the list of attachments.

We hope our report will be helpful.

Regards,

**Comment by sim0nx** [comment]
Hi,

Thanks for the report, unfortunately I am unable to reproduce this as I can't manage to create a ticket with only 1 attachment (there are always multiple). Any hints on how this can be done would appreciated (I am using RT/RT-IR 5.0.3).

**Comment by INCIBE-CERT** [comment]
Hi sim0nx

It's a bit tricky. You probably need a non-multipart message, and as soon as you start interacting with the ticket (perhaps even automatically by a scrip), you end up with multiple ones.

The following creates one such ticket here:
```
$ nc -C localhost 25
220 mailhost ESMTP Postfix (Debian/GNU)
EHLO hi
250-mailhost
250-PIPELINING
250-SIZE 30720000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250 8BITMIME
MAIL FROM:<>
250 2.1.0 Ok
RCPT TO:<instance@example.net>
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
From: someone@example.com
To: instance@example.net
Subject: test case

Hello world!
.
250 2.0.0 Ok: queued as A8B41322
quit
221 2.0.0 Bye
```
(adapting hostnames and email addresses as needed, ofc)

I'm testing with 4.4.1-3+deb9u4 but I don't think there will be much difference with 5.0 on the number of attachments it creates.

**Comment by sim0nx** [comment]
I was able to reproduce it and implemented a workaround, though I think this should be rather fixed upstream in RT.
Would be nice if you could open an issue in the RT project for this.

**Comment by INCIBE-CERT** [comment]
Thanks so much.

I'm not sure if it's really a bug in RT, though, since it seems unclear what is the correct output. The whole format seems to be a bit of whatever RT does. I see how it _may_ be a bug (in other cases it appears on its own line), but it could be argues as well that RT is by definition right.

Do you have a description on when the keys should be prepended by empty lines?

**Comment by INCIBE-CERT** [comment]
Yes, I had looked at https://rt-wiki.bestpractical.com/wiki/REST, but did not find a description on _why_ it's like that.
