### ISSUE TITLE
Retrieve the contents of a ticket

### ISSUE THREAD

**Issue by marvinwankersteen** [python-rt/python-rt#84]
Hey,
I am looking for a way to retrieve the contents of a ticket from Python and came across this project. I can't find a way to do this in BestPractical's documentation. The only possibility I know of is the Perl tool "rt" from BestPractical. With `rt show -l 6977` the content is shown. This script uses the REST API 1.0.

How can I get the content of the ticket with this project? Or is that not possible?

**Comment by sim0nx** [comment]
Hi,
Yes it is possible, you are looking for transactions which is described here:
https://docs.bestpractical.com/rt/5.0.2/RT/REST2.html#Transactions

In this lib, you would use a combination of https://python-rt.readthedocs.io/en/latest/rest2.html#rt.rest2.Rt.get_ticket_history and https://python-rt.readthedocs.io/en/latest/rest2.html#rt.rest2.Rt.get_transaction.

Hope that helps.
