### ISSUE TITLE
Issue with python 3.8.10

### ISSUE THREAD

**Issue by shanrahul** [python-rt/python-rt#85]
Hi, I'm using the python 3.8.10  and i installed rt (3.0.5), But when i run the following code

`from rt import RT`

I got the following as the error,

```
from rt import RT
ImportError: cannot import name 'RT' from 'rt' (/home/test/.local/lib/python3.8/site-packages/rt/__init__.py)
```

**Comment by sim0nx** [comment]
Hi,
Please have a look at the docs (https://python-rt.readthedocs.io/en/stable/rest1.html). If you are using the rest-v1 API, you should import RT like this:
```
from rt.rest1 import RT
```

for rest-v2 you do:
```
from rt.rest2 import RT
```
