### ISSUE TITLE
Password change has no implementation in the api.

### ISSUE THREAD

**Issue by eduardo-eurotux** [python-rt/python-rt#88]
After trying to use the edit_user function to change user's password, the following error is given:

`[error]: RT::User::Password Unimplemented in RT::Record.`

With this, is there a way to implement this feature? I would believe it would be hard, just because the password change is not implemented on the api.

**Comment by sim0nx** [comment]
Indeed it *should* work, but BP does not have everything implemented as functionality in the REST API.
You could request that with them and it should just work with the current python-rt code.
