### ISSUE TITLE
Sorting by order DESC in search() method doesn't work

### ISSUE THREAD

**Issue by rmengelle** [python-rt/python-rt#89]
Hello, 
I noticed an issue which is quite uncomfortable: 
Sorting by order DESC in `search()` method doesn't work (you can filter on `order="Created"` and `order="-Created"` to reproduce it)

https://github.com/python-rt/python-rt/blob/master/rt/rest2.py l.516-517 
In code we can see that only field name is sent to RT API with the param `orderby`, and, according to RT API documentation, it needs another param `order` to sort in an ascending/descending way (ASC default). When "-created" is sent nothing happens and the param `orderby` is just ignore.

BTW sending with curl the search request to RT API with orderby="Created"&order="DESC" works fine, as expected.
Can we have a fix to just add `get_params['order'] ="DESC"`   if the value is prefixed by "-" ?
I can do the PR if necessary.
Thanks

**Comment by sim0nx** [comment]
Hi
Thanks for the detailed report. I would appreciate a PR 🙂👍

**Comment by rmengelle** [comment]
Thanks for your quick answer. 
It's ready but I'm not allowed to push on a dedicated branch. Can you had me in ? Thanks

**Comment by rmengelle** [comment]
Done !
[PR 90 LINK](https://github.com/python-rt/python-rt/pull/90)

**Comment by sim0nx** [comment]
Thanks, appreciated!

**Comment by rmengelle** [comment]
Thanks to you for your work :)
