### ISSUE TITLE
error obtaining ticket history: get_ticket_history

### ISSUE THREAD

**Issue by jo-ze** [python-rt/python-rt#95]
Hi, 

I run an request tracker queue for testing. I used the latest rt.rest2 python package provided by pip
 (rt in ./mambaforge/lib/python3.10/site-packages (3.1.3) )
I used ubuntu 22.04.

import rt.rest2
import httpx
c = rt.rest2.Rt(url=api_url, token=token)

I am able to fetch the ticket meta data via 
        c.get_ticket(id)
but when I try to fetch the ticket history an error is thrown:
        c.get_ticket_history(ticket['id'])        
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 c.get_ticket_history(ticket['id']) 
      5 # have edited a try and except in line 315 on rest2.py
      6 #
      7 # 315             try:
   (...)
     12 # 320             except:
     13 # 321                 pass

File ~/mambaforge/lib/python3.10/site-packages/rt/rest2.py:655, in Rt.get_ticket_history(self, ticket_id)
    643 """ Get set of short history items
    644 
    645 :param ticket_id: ID of ticket
   (...)
    648           Returns None if ticket does not exist.
    649 """
    650 transactions = self.__paged_request(f'ticket/{ticket_id}/history', params={'fields': 'Type,Creator,Created,Description,_hyperlinks',
    651                                                                            'fields[Creator]': 'id,Name,RealName,EmailAddress',
    652                                                                            },
    653                                     )
--> 655 return list(transactions)

File ~/mambaforge/lib/python3.10/site-packages/rt/rest2.py:315, in Rt.__paged_request(self, selector, json_data, params, page, per_page, recurse)
    311     raise UnexpectedResponseError('Server returned an unexpected result')
    313 yield from result['items']
--> 315 if recurse and result['pages'] > result['page']:
    316     for _page in range(2, result['pages'] + 1):
    317         yield from self.__paged_request(selector, json_data=json_data, page=_page,
    318                                         per_page=result['per_page'], params=params, recurse=False)

TypeError: '>' not supported between instances of 'NoneType' and 'int'

I am confused and have changed the source code on rest2.py and added an exception to fix the problem.

 315             try:
 316                 if recurse and result['pages'] > result['page']:
 317                     for _page in range(2, result['pages'] + 1):
 318                         yield from self.__paged_request(selector, json_data=json_data, page=_page,
 319                                                     per_page=result['per_page'], params=params, recurse=False)
 320             except: 
 321                 pass

I am wondering if this is a bug?

**Comment by sim0nx** [comment]
Hi,

It is a bug (or "breaking change"), but unfortunately in RT, introduced in the latest version (5.0.5).

I have just merged a work-around which was pending as PR for some time. Please update to that (https://pypi.org/project/rt/3.1.4/) and retry.

(feel free to re-open if that does not fix your issue)
